version: "0.0"

services:
  uhppoted-rest:
    container_name: uhppoted-rest
    restart: unless-stopped
    image: ghcr.io/uhppoted/restd:latest
    volumes:
      - uhppoted:/var/uhppoted
      - ./uhppoted.conf:/var/uhppoted/etc/uhppoted.conf:ro
      - ./ca.cert:/var/uhppoted/rest/ca.cert:ro
      - ./uhppoted.cert:/var/uhppoted/rest/uhppoted.cert:ro
      - ./uhppoted.key:/var/uhppoted/rest/uhppoted.key:ro
    network_mode: "bridge"
    ports:
      - "8080:8080"
      - "8443:8443"

volumes:
  uhppoted:
    external: true
    name: uhppoted
